project:
  type: website
  output-dir: gh-pages

website:
  title: "Benjamin P. Stewart"
  navbar:
    left:
      - href: docs/index.qmd
        text: Home
      - href: docs/about.qmd
        text: Curriculum Vitae
      - href: docs/research.qmd
        text: Publications
      - href: docs/projects.qmd
        text: Projects

format:
  html:
    theme:
      - vapor      
    css: styles.css
    toc: true



