project:
  type: website
  output-dir: docs

website:
  title: "Benjamin P. Stewart"
  navbar:
    left:
      - href: quarto_docs/index.qmd
        text: Home
      - href: quarto_docs/about.qmd
        text: Curriculum Vitae
      - href: quarto_docs/research.qmd
        text: Publications
      - href: quarto_docs/projects.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo      
    css: styles.css
    toc: true



